# Generated by Django 4.1 on 2022-09-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created_at']},
        ),
    ]
