# Generated by Django 4.1 on 2022-08-31 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='CATEGORY'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cartegory',
            field=models.CharField(blank=True, default='Sport', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newss', to='news.new'),
        ),
    ]
